### ISSUE TITLE
fatal error: memory: No such file or directory  #include <memory>

### ISSUE THREAD

**Issue by PatrikForis** [matth-x/ArduinoOcpp#61] opened 2022-04-26 14:59 UTC
Hello. I am trying to compile code form examples of this project but I got fatal error message and I can´t move on. Can somebody please help with solution of this error?

![eroro](https://user-images.githubusercontent.com/104420989/165330112-e5f51c00-7e49-44ec-8a42-121816d2ab43.png)

**Comment by marcos-mendez** [comment] 2022-05-02 17:22
You are running the compilation on wrong settings in the Arduino IDE. Recommend closing the Issue.

**Comment by PatrikForis** [comment] 2022-05-03 06:13
Thank you for answer, but which setting should I change.

**Comment by marcos-mendez** [comment] 2022-05-03 11:19
I should check it personally but you have to check mainly board settings

**Comment by matth-x** [comment] 2023-01-07 17:11
Sorry, couldn't reproduce this.

Closed due to inactivity. Please reopen for follow-up questions.

**Closed by matth-x** 2023-01-07 17:11 UTC
