### ISSUE TITLE
Bug report in OperationsQueue.cpp

### ISSUE THREAD

**Issue by ag-prn** [matth-x/ArduinoOcpp#135] opened 2023-04-03 16:03 UTC
https://github.com/matth-x/ArduinoOcpp/blob/a41ae50aeabc042c6b64800f0518c3fe39abb0be/src/ArduinoOcpp/Core/OperationsQueue.cpp#L91
This line must be 
else if (!fetched->isFullyConfigured()) {

or we can get panic reaction after fetched.reset() in
            if (!success) {
                AO_DBG_ERR("could not restore operation");
                fetched.reset();
            }

**Comment by matth-x** [comment] 2023-04-19 17:48
Hi @ag-prn,

Many thanks for taking the time to write an error report. In this case, the issue is already resolved in the develop branch and now I have one further reason to speed up with merging everything to main!

**Closed by matth-x** 2023-04-19 17:48 UTC
