### ISSUE TITLE
How to setup the project?

### ISSUE THREAD

**Issue by adithyagurumurthy** [matth-x/ArduinoOcpp#33] opened 2021-11-14 08:03 UTC
I am using NodeMcuv2
I have downloaded the project, and selected the moved the examples file "ESP/mail.ino" into the source file, but still I am getting errors 
![image](https://user-images.githubusercontent.com/29145773/141672796-59d4d79c-c2fd-4089-8a32-6056d92bfd4f.png)

How should I setup the project, I am unbale to do it.
Detailed Step would be really helpful

**Comment by adithyagurumurthy** [comment] 2021-11-14 14:25
I was somehow able to resolve the error , but I see a new wierd characters in console
![image](https://user-images.githubusercontent.com/29145773/141685278-257bb52d-a3a2-4fa1-b3fa-14cad5b95e30.png)

Is this intended ? how to correct this ?

**Comment by matth-x** [comment] 2021-11-14 23:00
Hi Adithya,

Yes, the first errors likely occured because of a version jump in the develop branch. Thank you for reporting this, should be fixed. The second screenshot just shows that the console is somehow misconfigured. Maybe your `platformio.ini` is missing the line `monitor_speed = 115200`?

**Comment by adithyagurumurthy** [comment] 2021-11-15 02:53
Thanks will look into that and try to compile!!

**Comment by adithyagurumurthy** [comment] 2021-11-17 16:38
I try to compile and the websocket are not working ,
![image](https://user-images.githubusercontent.com/29145773/142242637-2888fb9d-79c9-46f2-a3e7-fd5aacd3a496.png)

I dont see any connection established to websocekts.
How to establish the websocket ?

**Comment by HackLink123** [comment] 2021-12-16 07:20
Hi adithyagurumurthy  I met the same problem as you.Can you tell me the solution? Thank you so much.

**Comment by HackLink123** [comment] 2021-12-21 03:54
The problem is that the  (Espressif 8266) version  too high
I solved the above problem and used the following methods:
![image](https://user-images.githubusercontent.com/20769079/146868041-beaa9c6c-22ec-4eda-980f-8641109af8c1.png)
Change you Espressif 8266 version in **2.6.3** .

**Comment by matth-x** [comment] 2021-12-21 08:38
Hi, thank you! I will adapt the `platformio.ini` according to your report.

**Comment by matth-x** [comment] 2022-02-02 09:59
@adithyagurumurthy Please refer to https://github.com/matth-x/ArduinoOcpp/issues/36#issuecomment-989716573.

**Closed by matth-x** 2022-02-02 09:59 UTC
